### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ReleLes** [ReleLes/furima-30539#11]
フリマアプリのURL 
https://furima-30539.herokuapp.com/

Basic認証のIDとパスワード
ユーザー： test
パスワード： 0628

出品者用のメールアドレスとパスワード
メールアドレス： test@test.com
パスワード： 123abc

購入者用のメールアドレスとパスワード
メールアドレス： sample@sample.com
パスワード： 123abc

購入用カードの番号・期限・セキュリティコード
カード番号：4242424242424242
期限：3 / 23
セキュリティーコード：123

**Comment by sho0127** [comment]
ReleLesさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
